language: python

env:
 - DJANGO_VERSION=1.8.16
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.3

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "pypy"

install:
 - pip install -q Django==$DJANGO_VERSION

script:
 - python runtests.py
